### Understanding the Import
In order to make the code more readable, we have to import the numpy as "**np**" as it is a sort of universal convention followed across the python community. 

Creating an array which consists of two elements [1,2,3,4] and [5,6,7,8]

In [74]:
import numpy as np

my_array=np.array([[1,2,3,4],[5,6,7,8]], dtype=np.int64)
print(my_array)

print("Dtype",my_array.dtype)
print("Data:",my_array.data)
print("Shape:",my_array.shape)
print("Strides:", my_array.strides)

[[1 2 3 4]
 [5 6 7 8]]
Dtype int64
Data: <memory at 0x7fc4d30403a8>
Shape: (2, 4)
Strides: (32, 8)


In [75]:
print(np.ones((3,2)))

np.empty((3,2))

[[ 1.  1.]
 [ 1.  1.]
 [ 1.  1.]]


array([[ 1.,  1.],
       [ 1.,  1.],
       [ 1.,  1.]])

In [76]:
#Creating identity matrices
print(np.eye(2,2))

#Alternatively, using identity()
three_by_three_identity=np.identity(3)
print("\n \t\t\t\t\t 3x3 Identity Matrix: \n",three_by_three_identity)

[[ 1.  0.]
 [ 0.  1.]]

 					 3x3 Identity Matrix: 
 [[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [77]:
#Metrics for matrices
print("Size:",three_by_three_identity.size)          #using size()
print("Dimensions:",three_by_three_identity.ndim)    #using ndim()
print("\nFlags: \n",three_by_three_identity.flags)   #using flags()
print("\nNumber fo Bytes: ",three_by_three_identity.nbytes, "\n") #using nbytes()
print("Itemsize:",three_by_three_identity.itemsize)  #using itemsize()

Size: 9
Dimensions: 2

Flags: 
   C_CONTIGUOUS : True
  F_CONTIGUOUS : False
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  UPDATEIFCOPY : False

Number fo Bytes:  72 

Itemsize: 8


### Tweaking the Array
We can compute the **length()**, change the data type and perform many such similarily required operations in order to tweak the numpy array.

In [84]:
#Chainging datatype of array to float
print("\nFloat array:")
print(three_by_three_identity.astype(float))   #changing to float
print("\n String array:")
print(three_by_three_identity.astype(str))      #changing to string
print("\nInteger array:")
print(three_by_three_identity.astype(int))      #changing to int
print("\nLogical array:")
print(three_by_three_identity.astype(bool))    #Interestingly, we can also change the array elements to logical

#The logical array will have all elements as TRUE if the value os non zero and FALSE if the value is zero


Float array:
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]

 String array:
[['1.0' '0.0' '0.0']
 ['0.0' '1.0' '0.0']
 ['0.0' '0.0' '1.0']]

Integer array:
[[1 0 0]
 [0 1 0]
 [0 0 1]]

Logical array:
[[ True False False]
 [False  True False]
 [False False  True]]


### Mathematical Operations
* Adding two matrices

In [114]:
mat1=np.eye(2);
print(mat1)
mat2=np.array([[1,2],[3,4]])
print("\nMatrix 2:\n", mat2)
mat3=mat1+mat2;
print(mat3)
print(type(mat1))


#Computing remainder
print("\nComputing the remainder of mat2 when divided by mat1 elementwise: \n")
print(np.remainder(mat1,mat2)) #this fucntion computes the remainder (or, modulus) through an elementwise operation


[[ 1.  0.]
 [ 0.  1.]]

Matrix 2:
 [[1 2]
 [3 4]]
[[ 2.  2.]
 [ 3.  5.]]
<class 'numpy.ndarray'>

Computing the remainder of mat2 when divided by mat1 elementwise: 

[[ 0.  0.]
 [ 0.  1.]]


In [117]:
print(np.add(mat1, mat2)) #Adding the matrices mat1 and mat2 through elementwise operations
#Alternatively, we can store the result and then print in case the result matrix is required for further use
mat3=np.add(mat1, mat2); 
print("\n",mat3)


[[ 2.  2.]
 [ 3.  5.]]

 [[ 2.  2.]
 [ 3.  5.]]


In [122]:
print("Minimum value in Matrix 2:",mat2.min())
print("Maximum value in Matrix 2:",mat2.max())

Minimum value in Matrix 2: 1
Maximum value in Matrix 2: 4


In [132]:
# Computing the mean of all values in a matrix
print("Mean value in Matrix 1:", mat1.mean())

print("Mean value in Matrix 1:", mat1[1:,1].mean())
print("Mean value in Matrix 2:", mat2[0:,0].mean()) 


Mean value in Matrix 1: 0.5
Mean value in Matrix 1: 1.0
Mean value in Matrix 2: 2.0


Observe that, we can compute the mean value of any of the parts of a given matrix by subsetting it suitably. For example, If we are interested in finding the mean value of first row of Matrix 2, which has the elements '1' and '2', then we must subset the Matrix 2 in such a way that the function **mean( )** is applied only on that subset of the Matrix 2. In our case, we have the mean of the elements '1' and '2' equal to 1.5 . Let us verify it computationally.

**NOTE:** The use of colon(:) operator is made for **selecting all** in a sequence of values. For e.g. if we write that '1:' then it can be interpreted as "select all values in that particular sequence starting from 1 onwards"

In [152]:
#print("Mean value in Matrix 2:", mat2[0:,].mean()) 
print("Elements in first row of Matrix 2:", mat2[0,0:])    #It is like choosing all columns in the first row
print("Mean of first row in Matrix 2:", mat2[0,0:].mean()) 
print("Elements in second column of Matrix 2:", mat2[0:,1]) #It is like choosing all rows in second column
print("Mean of second column in Matrix 2:", mat2[0:,1].mean()) 


Elements in first row of Matrix 2: [1 2]
Mean of first row in Matrix 2: 1.5
Elements in second column of Matrix 2: [2 4]
Mean of second column in Matrix 2: 3.0


**NOTE**: An important fact worth attention is that the index of elements in an numpy array begins from '0' and not '1' which is quite commonly seen in matrices in other programming languages. 

### Comparison Operations
We can also perform operations to compare the each of the elements of two arrays. The following code achieves this objective-

In [179]:
mat1=np.zeros((3,3));
print(mat1);
mat2=np.random.random((3,3));
print(mat2)

#finally, add the two together in and store the result in a third matrix as "mat3"
mat3=mat1+mat2;
print(np.array_equal(mat1, mat3))
print(np.array_equal(mat2, mat3))

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
[[ 0.34699457  0.96379954  0.24088279]
 [ 0.47434466  0.66795359  0.8128835 ]
 [ 0.16707271  0.93392289  0.67906784]]
False
True
